import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',c='33333333-3333-4333-8333-333333333333';
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;insert into auth.users values('${a}'),('${b}'),('${c}');`);
await db.exec(await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8'));
await db.exec('grant usage on schema public to authenticated;grant select,insert,update,delete on all tables in schema public to authenticated;');
async function as(id){await db.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);set role authenticated`)}
await as(a);
const group=(await db.query("select * from create_study_group('M3101')")).rows[0];
const shared=(await db.query(`insert into tasks(user_id,group_id,title,subject,due_at,reminder_minutes) values($1,$2,'Общее','Матанализ',now()+interval '30 minutes',60) returning id`,[a,group.id])).rows[0].id;
const personal=(await db.query(`insert into tasks(user_id,title,subject,due_at,reminder_minutes) values($1,'Личное','Физика',now()+interval '30 minutes',60) returning id`,[a])).rows[0].id;
await as(c);assert.equal((await db.query('select * from tasks')).rows.length,0);
await assert.rejects(()=>db.query(`insert into tasks(user_id,group_id,title,subject,due_at) values($1,$2,'Чужое','Тест',now())`,[c,group.id]),/row-level security/);
await assert.rejects(()=>db.query('select * from claim_reminders()'),/permission denied/);
await as(b);await db.query('select * from join_study_group($1)',[group.invite_code]);
assert.deepEqual((await db.query('select id from tasks')).rows.map(x=>x.id),[shared]);
await db.query(`insert into tasks(user_id,group_id,title,subject,due_at,reminder_minutes) values($1,$2,'От участника','Физика',now()+interval '2 days',0)`,[b,group.id]);
assert.equal((await db.query('delete from tasks where id=$1 returning id',[shared])).rows.length,0);
assert.equal((await db.query("update tasks set title='Испорчено' where id=$1 returning id",[shared])).rows.length,0);
await as(a);
assert.equal((await db.query("update tasks set title='Уточнено' where id=$1 returning id",[shared])).rows.length,1,'author edits own shared task');
await assert.rejects(()=>db.query('update tasks set group_id=null where id=$1',[shared]),/не меняются/);
await assert.rejects(()=>db.query('update tasks set user_id=$2 where id=$1',[shared,b]),/не меняются/);
const throwaway=(await db.query(`insert into tasks(user_id,group_id,title,subject,due_at,reminder_minutes) values($1,$2,'Опечатка','Тест',now()+interval '1 day',10080) returning id`,[a,group.id])).rows[0].id;
assert.equal((await db.query('delete from tasks where id=$1 returning id',[throwaway])).rows.length,1,'author deletes own shared task');
await assert.rejects(()=>db.query(`insert into tasks(user_id,title,subject,due_at,reminder_offsets) values($1,'Чужой интервал','Тест',now(),'{7}')`,[a]),/reminder_offsets/);
assert.equal((await db.query("update tasks set completed=true where id=$1 returning id",[personal])).rows.length,1,'personal task goes to archive');
await db.query('update tasks set completed=false where id=$1',[personal]);
assert.equal((await db.query('select * from tasks')).rows.length,3);
await db.exec('reset role');
await db.query(`insert into push_subscriptions(user_id,endpoint,subscription,hidden_task_ids) values($1,'https://test/a','{}',$4),($2,'https://test/b','{}','{}'),($3,'https://test/c','{}','{}')`,[a,b,c,[shared]]);
const claimed=(await db.query('select * from claim_reminders()')).rows;
assert.equal(claimed.length,2);
assert(claimed.some(r=>r.task_id===shared&&r.user_id===b));
assert(claimed.some(r=>r.task_id===personal&&r.user_id===a));
assert.equal((await db.query('select * from claim_reminders()')).rows.length,0,'locked deliveries cannot be reclaimed');
await db.exec('update reminder_deliveries set sent_at=now(),claimed_at=null');
assert.equal((await db.query('select * from claim_reminders()')).rows.length,0,'sent reminders cannot be duplicated');
// несколько напоминаний на одно задание дают несколько слотов
await as(a);
const many=(await db.query(`insert into tasks(user_id,title,subject,due_at,reminder_offsets) values($1,'Курсовая','Программирование',now()+interval '50 minutes','{0,60,1440}') returning id`,[a])).rows[0].id;
await db.exec('reset role');
const slots=(await db.query('select * from claim_reminders()')).rows.filter(r=>r.task_id===many);
assert.equal(slots.length,2,'уже наступившие напоминания за день и за час взяты, «в срок» ещё нет');
assert.equal((await db.query('select * from claim_reminders()')).rows.filter(r=>r.task_id===many).length,0,'каждый слот забирается один раз');
await db.query('delete from tasks where id=$1',[many]);

// повтор — это расписание push, срок при этом не двигается
await as(a);
const dueAt=(await db.query('select due_at from tasks where id=$1',[personal])).rows[0].due_at;
const daily=(await db.query(`insert into tasks(user_id,title,subject,due_at,reminder_minutes,repeat_rule,repeat_time) values($1,'Английские слова','Английский',now()+interval '20 days',0,'daily',(now() at time zone 'Europe/Moscow')::time - interval '5 minutes') returning id`,[a])).rows[0].id;
await assert.rejects(()=>db.query(`insert into tasks(user_id,title,subject,due_at,repeat_rule) values($1,'Без времени','Тест',now()+interval '1 day','daily')`,[a]),/repeat_time/);
await assert.rejects(()=>db.query(`update tasks set repeat_rule='hourly' where id=$1`,[daily]),/repeat_rule/);
await db.exec('reset role');
await db.query(`insert into push_subscriptions(user_id,endpoint,subscription) values($1,'https://test/daily','{}')`,[a]).catch(()=>{});
const repeatClaim=(await db.query('select * from claim_reminders()')).rows.filter(r=>r.task_id===daily);
assert.equal(repeatClaim.length,1,'repeating task is claimed for its slot today');
assert(new Date(repeatClaim[0].slot)<=new Date(),'slot is in the past');
assert.equal((await db.query('select * from claim_reminders()')).rows.filter(r=>r.task_id===daily).length,0,'one push per slot');
assert.equal((await db.query('select due_at from tasks where id=$1',[personal])).rows[0].due_at.getTime(),dueAt.getTime(),'сроки не двигаются');
assert.equal((await db.query('select count(*)::int c from reminder_deliveries where task_id=$1',[daily])).rows[0].c,1,'delivery is tracked per slot');
await db.query('delete from tasks where id=$1',[daily]);
await db.exec('update reminder_deliveries set sent_at=now(),claimed_at=null');
await as(a);await db.query("update tasks set due_at=now()+interval '35 minutes' where id=$1",[personal]);
await db.exec('reset role');assert.equal((await db.query('select * from claim_reminders()')).rows.length,1,'rescheduled personal deadline is eligible again');
await db.close();console.log('PASS: group membership, personal isolation, member creation, author-only editing, immutable owner and group, archive flag, per-recipient delivery, device hiding, retry locks, repeating push slots, multiple reminders and rescheduling.');
